#pragma once
#include <JuceHeader.h>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstring>

enum class SnairMode { snare = 0, clap = 1 };

// Stable public parameter IDs (design spec §12). Never rename or reuse an ID.
namespace ParamIDs
{
inline constexpr const char* mode = "mode";
inline constexpr const char* sourceCharacter = "source_character";
inline constexpr const char* punch = "punch";
inline constexpr const char* snap = "snap";
inline constexpr const char* body = "body";
inline constexpr const char* texture = "texture";
inline constexpr const char* dirt = "dirt";
inline constexpr const char* size = "size";
inline constexpr const char* bodyFreqHz = "body_freq_hz";
inline constexpr const char* attack = "attack";
inline constexpr const char* noise = "noise";
inline constexpr const char* tailMs = "tail_ms";
inline constexpr const char* pitchSt = "pitch_st";
inline constexpr const char* tone = "tone";
inline constexpr const char* driveDb = "drive_db";
inline constexpr const char* width = "width";
inline constexpr const char* clapCount = "clap_count";
inline constexpr const char* clapSpreadMs = "clap_spread_ms";
inline constexpr const char* crossBlend = "cross_blend";
inline constexpr const char* outputTrimDb = "output_trim_db";
inline constexpr const char* normalizeRender = "normalize_render";
inline constexpr const char* seed = "seed";
// v0.0.1 additions
inline constexpr const char* room = "room";          // gated room effect amount (render)
inline constexpr const char* keyTrack = "key_track"; // chromatic MIDI playback (playback only)
}

// Seeds generated by Randomize/Mutate stay below 2^24 so they survive float host automation exactly.
inline constexpr uint32_t maxGeneratedSeed = 999999u;

struct SnairParameters
{
    SnairMode mode = SnairMode::snare;
    float sourceCharacter = 0.5f;
    float punch = 0.5f;
    float snap = 0.5f;
    float body = 0.5f;
    float texture = 0.5f;
    float dirt = 0.2f;
    float size = 0.5f;
    float bodyFreqHz = 190.0f;
    float attack = 0.5f;
    float noise = 0.5f;
    float tailMs = 300.0f;
    float pitchSt = 0.0f;
    float tone = 0.0f;
    float driveDb = 3.0f;
    float width = 0.5f;
    int clapCount = 4;
    float clapSpreadMs = 18.0f;
    float crossBlend = 0.0f;
    float outputTrimDb = 0.0f;
    bool normalizeRender = true;
    uint32_t seed = 1u;
    float room = 0.0f;
    bool keyTrack = false;

    void sanitize() noexcept
    {
        auto c=[](float v,float lo,float hi,float d){ return std::isfinite(v)?std::clamp(v,lo,hi):d; };
        sourceCharacter=c(sourceCharacter,0,1,0.5f); punch=c(punch,0,1,0.5f); snap=c(snap,0,1,0.5f);
        body=c(body,0,1,0.5f); texture=c(texture,0,1,0.5f); dirt=c(dirt,0,1,0.2f); size=c(size,0,1,0.5f);
        bodyFreqHz=c(bodyFreqHz,70,450,190); attack=c(attack,0,1,0.5f); noise=c(noise,0,1,0.5f);
        tailMs=c(tailMs,20,2000,300); pitchSt=c(pitchSt,-24,24,0); tone=c(tone,-1,1,0); driveDb=c(driveDb,0,24,3);
        width=c(width,0,1,0.5f); clapCount=std::clamp(clapCount,2,6); clapSpreadMs=c(clapSpreadMs,8,35,18);
        crossBlend=c(crossBlend,0,1,0); outputTrimDb=c(outputTrimDb,-24,12,0); room=c(room,0,1,0);
        seed=std::min<uint32_t>(seed,2147483647u);
        if(mode!=SnairMode::snare && mode!=SnairMode::clap) mode=SnairMode::snare;
    }

    // Hash of every value that affects the offline render (excludes playback-only trim/key tracking).
    uint64_t renderHash() const noexcept
    {
        uint64_t h=1469598103934665603ull;
        auto mix=[&h](uint32_t v){ h^=v; h*=1099511628211ull; };
        auto f=[&mix](float v){ uint32_t u; std::memcpy(&u,&v,sizeof u); mix(u); };
        mix(static_cast<uint32_t>(mode)); f(sourceCharacter); f(punch); f(snap); f(body); f(texture); f(dirt);
        f(size); f(bodyFreqHz); f(attack); f(noise); f(tailMs); f(pitchSt); f(tone); f(driveDb); f(width);
        mix(static_cast<uint32_t>(clapCount)); f(clapSpreadMs); f(crossBlend); mix(normalizeRender?1u:0u);
        mix(seed); f(room);
        return h;
    }
};
